name: OSM-Ess
main: com.oldschoolminecraft.OSMEss.OSMEss
version: 1.0
authors: [SavageUser, moderator_man, ItsVollx]
depend:
  - Essentials
softdepend:
  - Invisiman
  - Landmarks
  - PermissionsEx

commands:
  baltop:
    aliases: [balancetop]
    description: Shows a list of the top 10 players' balance.
  ignorebroadcast:
    aliases: [ignorebroadcasts]
    description: Toggles visibility of the auto broadcast messages.
  list:
    aliases: [online]
    description: Shows a list of online players.
  ptt:
    description: Shows a list of the top 10 longest played players.
  seen:
    description: Shows info on a player's playtime, first join date, and more.
  staff:
    description: Toggles staff mode.


