name: OSM-Ess
main: com.oldschoolminecraft.OSMEss.OSMEss
version: 1.4.5
authors: [SavageUser, moderator_man, ItsVollx]
depend:
  - Essentials
softdepend:
  - Invisiman
  - Landmarks
  - Lockette
  - OSAS
  - PermissionsEx
  - ScheduledDeath

commands:
  auction:
    description: Starts an action with the item you're holding.
  baltop:
    aliases: [balancetop]
    description: Shows a list of the top 10 players' balance.
  bid:
    description: Places a bid on an active auction.
  chatcolor:
    aliases: [cc]
    description: Sets the color of the message typed in public chat.
  confirmbid:
    description: Confirms a bid you have on hold.
  denybid:
    description: Denies a bid you have on hold.
  discord:
    description: Gives you the link to the discord server.
  ea:
    description: Toggles explosive arrows.
  findhome:
    description: Searches for any existing home with the given characters.
  forecast:
    description: Shows the weather forecast.
  highlightwarp:
    description: Highlights an existing warp to a specific color.
  home:
    description: Shows your homes in normal form.
  homes:
    description: Shows your homes in page form.
  ignorebroadcast:
    aliases: [ignorebroadcasts]
    description: Toggles visibility of the auto broadcast messages.
  list:
    aliases: [online]
    description: Shows a list of online players.
  osmess:
    description: OSM-Ess administration commands.
  ptt:
    description: Shows a list of the top 10 longest played players.
  rainbow:
    description: Gives you a rainbow name.
  seen:
    description: Shows info on a player's playtime, first join date, and more.
  settimezone:
    description: Change the time zone format for /seen and more.
  setwarp:
    description: Creates a new warp.
  staff:
    description: Toggles staff mode.
  warn:
    description: Warns a player.
  warnings:
    description: Shows a player's list of warnings, or choose to clear them.
  warp:
    description: Shows a list of warps to teleport to.
  whitelist:
    description: Shows a list of whitelist commands.
